### ISSUE TITLE
Certbot 13 Segmentation fault

### ISSUE THREAD

**Issue by kurniawan77** [bestlibre/hassio-addons#111]
After updating certbot from 0.18 to .19 i get this error in the log:

/run.sh: line 28:    13 Segmentation fault      (core dumped) certbot certonly $PLUGIN --non-interactive --email "$EMAIL" --agree-tos --config-dir "$CERT_DIR" --work-dir "$WORK_DIR" --cert-name $name -d ${domains}

**Comment by bestlibre** [comment]
Can you give me your arch?

**Comment by kurniawan77** [comment]
not sure. how can i find that?

**Comment by bestlibre** [comment]
What is your device? And I think you can find some info on the hassio system tab.

**Comment by kurniawan77** [comment]
![image](https://user-images.githubusercontent.com/3305888/54864279-6abf6d80-4d55-11e9-9159-96d371e88174.png)
Same thing goes for the NGINX addon, updating it result with:
/run.sh: line 16:    11 Segmentation fault      (core dumped) python3 /mustache.py /templates/vhost.mustache /data/options.json > /etc/nginx/conf.d/vhosts.conf

**Comment by bestlibre** [comment]
I will try to have a look at this problem ASAP. Probably not before Monday.

**Comment by kurniawan77** [comment]
oke no probs. reverted back by a snapshot, so everything is fine again here

**Comment by kurniawan77** [comment]
Additional info:
Arch: aarch64

Tried the Caddy addon, getting errors there too...

**Comment by bestlibre** [comment]
Can you try with the last version ?

**Comment by kurniawan77** [comment]
Still errors... i get segmentation errors with nginx, caddy and this (certbot) addons.

aarch64 Hassio

certbot log:
/run.sh: line 28:    14 Segmentation fault      (core dumped) certbot certonly $PLUGIN --non-interactive --email "$EMAIL" --agree-tos --config-dir "$CERT_DIR" --work-dir "$WORK_DIR" --cert-name $name -d ${domains}

**Comment by kurniawan77** [comment]
I tried Caddy once again. This time i get the .5-1 version and it works! I will try the nginx and certbot addon later when i get back from work

**Comment by kurniawan77** [comment]
Still the same error on certbot.

And in nginx i get these:

Traceback (most recent call last):
  File "/mustache.py", line 31, in <module>
    render(args.template, args.data)
  File "/mustache.py", line 23, in render
    print(renderer.render_path(template, context))
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 390, in render_path
    return self._render_string(template, *context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 402, in _render_string
    return self._render_final(render_func, *context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 419, in _render_final
    return render_func(engine, stack)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 400, in <lambda>
    render_func = lambda engine, stack: engine.render(template, stack)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderengine.py", line 179, in render
    parsed_template = parse(template, delimiters)
  File "/usr/local/lib/python3.7/site-packages/pystache/parser.py", line 41, in parse
    return parser.parse(template)
  File "/usr/local/lib/python3.7/site-packages/pystache/parser.py", line 320, in parse
    raise ParsingError("Section end tag mismatch: %s != %s" % (tag_key, section_key))
pystache.parser.ParsingError: Section end tag mismatch: remote_ssl}://{{#remote != remote_ssl

**Comment by rbray89** [comment]
I'm seeing the same with certbot (no issues with nginx) on an aarch64 device.

**Comment by rbray89** [comment]
This was resolved for me once I cleaned up some disk full issues.
