### ISSUE TITLE
Nginx Proxy errors after update to 0.1.13

### ISSUE THREAD

**Issue by jkms** [bestlibre/hassio-addons#116]
After updating to 0.1.13, my Nginx Proxy fails to start.

Previous version was 0.1.12, which worked fine.

Config:
```
{
  "vhosts": [
    {
      "vhost": "home.domain.tld",
      "certname": "domaincert",
      "port": "8123",
      "default_server": true
    },
    {
      "remote": "192.168.1.62",
      "vhost": "music.domain.tld",
      "certname": "domaincert",
      "port": "4040"
    },
    {
      "remote": "192.168.1.61",
      "vhost": "portal.domain.tld",
      "certname": "domaincert",
      "port": "80"
    },
    {
      "remote": "192.168.1.30",
      "vhost": "transmission.domain.tld",
      "certname": "domaincert",
      "port": "9091"
    },
    {
      "remote": "192.168.1.61",
      "vhost": "sonarr.domain.tld",
      "certname": "domaincert",
      "port": "8989"
    },
    {
      "remote": "192.168.1.61",
      "vhost": "radarr.domain.tld",
      "certname": "domaincert",
      "port": "7878"
    },
    {
      "remote": "192.168.1.30",
      "vhost": "nas.domain.tld",
      "certname": "domaincert",
      "port": "80"
    }
  ]
}
```

This is my log:
```
Traceback (most recent call last):
  File "/mustache.py", line 31, in <module>
    render(args.template, args.data)
  File "/mustache.py", line 23, in render
    print(renderer.render_path(template, context))
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 390, in render_path
    return self._render_string(template, *context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 402, in _render_string
    return self._render_final(render_func, *context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 419, in _render_final
    return render_func(engine, stack)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderer.py", line 400, in <lambda>
    render_func = lambda engine, stack: engine.render(template, stack)
  File "/usr/local/lib/python3.7/site-packages/pystache/renderengine.py", line 179, in render
    parsed_template = parse(template, delimiters)
  File "/usr/local/lib/python3.7/site-packages/pystache/parser.py", line 41, in parse
    return parser.parse(template)
  File "/usr/local/lib/python3.7/site-packages/pystache/parser.py", line 320, in parse
    raise ParsingError("Section end tag mismatch: %s != %s" % (tag_key, section_key))
pystache.parser.ParsingError: Section end tag mismatch: remote_ssl}://{{#remote != remote_ssl
```

**Comment by buckbanzai** [comment]
I'm having the exact same issue after upgrading.

**Comment by SvenNederhoff** [comment]
Same issue here,

**Comment by jkms** [comment]
I think  #117 fixes the code, but something else needs to happen in order for the update to appear in HassIO. @bestlibre can you work your magic? :)

**Comment by buckbanzai** [comment]
@jkms I found that uninstalling and reinstalling the addon seemed to download the new version, but it does have the same version number.

**Comment by jkms** [comment]
> 
> 
> @jkms I found that uninstalling and reinstalling the addon seemed to download the new version, but it does have the same version number.

That worked! Thanks @buckbanzai

**Comment by bestlibre** [comment]
Version bump done. Should be fixed. Sorry for the delay.

**Comment by jkms** [comment]
Working great as of be883b162d032fdafde4b372b68dc0ba4ce3d747. Thanks @bestlibre
