### ISSUE TITLE
Unable to set volume or mute state on snapcast clients

### ISSUE THREAD

**Issue by torsk** [bestlibre/hassio-addons#88]
I'm using the "Mopidy and Snapcast" addon. Since the update to HA version 0.80 I'm not able to set volume or mute state of my snapcast clients through HA user interface (the snapcast UI on my smartphones is still working). Volume value and mute state are shown correctly in HA but to control them via HA is impossible for me.

From /config/home-assistant.log:

```
2018-10-16 10:28:22 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 226, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/snapcast.py", line 244, in async_mute_volume
    await self._client.set_muted(mute)
TypeError: object generator can't be used in 'await' expression
```

**Comment by torsk** [comment]
Seems it has been a bug in HA itself. Since update to version 0.80.3 snapcast is working again.
